# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'MySpot' do
    pod 'Mapbox-iOS-SDK'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Eureka'
end

